[ARC-1830]added local database and build flavor
AleksandreGalogreBaramidze/MovieApp pull request #5
Opened 2021-10-28 08:58 UTC by AleksandreGalogreBaramidze

https://spaceneobank.atlassian.net/browse/ARC-1830

2021-11-01 07:33 UTC, giorgiqemoklidze requested changes

2021-11-01 07:33 UTC, giorgiqemoklidze commented on app/src/main/java/com/example/movieapp/adapters/HomeRecyclerAdapter.kt
> +        data.forEach { favoriteMovies.add(Movie.Result(it.poster, it.id, "unknown", "unknown", 0.0, "unknown", "unknown","",false, null)) }
data კლასში გაუწერე results default value ები და ეს ერთი მოდელ კლასიდან მეორეში გადაყვანა გაიტანე ფრაგმენტს გარეთ :დ პ.ს მეც იგივე შეცდომა მაქ :დ უნდა დავარეფაქტორო

2021-11-01 07:37 UTC, GiorgiMamagulashvili16 commented on app/src/main/java/com/example/movieapp/adapters/HomeRecyclerAdapter.kt
> +        holder.binding.mainImage.load(holder.binding.root.context, BASE_PICTURE_URL + (item.backdrop_path))
ცალკე ფუნქციაში გაიტანე კონსტანტების გამოყენება რო აღარ მოგიწიოს

2021-11-01 07:40 UTC, GiorgiMamagulashvili16 commented on app/src/main/java/com/example/movieapp/di/Module.kt
> +    fun getMoviesData(): RetrofitService = Retrofit.Builder().baseUrl(BASE_URL).addConverterFactory(GsonConverterFactory.create()).build().create(RetrofitService::class.java)
ცალ-ცალკე შექმენი retrofit და სერვისის პროვაიდი

2021-11-01 07:43 UTC, GiorgiMamagulashvili16 commented on app/src/main/java/com/example/movieapp/movies_detail/MoviesDetailScreenViewModel.kt
> +    }
სახელები შეუცვალე :დ

2021-11-01 10:20 UTC, andguladzeshio approved these changes

2021-11-01 10:24 UTC, AnaRusadze requested changes

2021-11-01 10:24 UTC, AnaRusadze commented on app/src/main/java/com/example/movieapp/adapters/HomeRecyclerAdapter.kt
> +class HomeRecyclerAdapter : RecyclerView.Adapter<HomeRecyclerAdapter.ViewHolder>() {
სახელი

2021-11-01 10:24 UTC, AnaRusadze commented on app/src/main/java/com/example/movieapp/adapters/HomeRecyclerAdapter.kt
> +        holder.binding.mainImage.setOnClickListener {
with(holder.binding)

2021-11-01 10:24 UTC, AnaRusadze commented on app/src/main/java/com/example/movieapp/movies/Movies.kt
ფრაგმენტის სახელი

2021-11-01 10:24 UTC, AnaRusadze commented on app/src/main/java/com/example/movieapp/movies/Movies.kt
> +    private var internetCheckerBoolean: Boolean? = null
private var isPopular by Delegates.notNull<Boolean>()
    private var internetCheckerBoolean: Boolean? = null
ეს ცვლადები ვიუმოდელში უნდა იყოს

2021-11-01 10:24 UTC, AnaRusadze commented on app/src/main/java/com/example/movieapp/movies/Movies.kt
> +    private fun connectionHandler() {
ინტერნეტ ქონექშენის ლოგიკა ვიუ მოდელს ეკუთვნის

2021-11-01 10:24 UTC, AnaRusadze commented on app/src/main/java/com/example/movieapp/movies/Movies.kt
> +                        if(it.message == "Unable to resolve host \"api.themoviedb.org\": No address associated with hostname"){
ეს ჩეკი შესაცვლელია. ერორის კოდის მიხედვით უნდა შემოწმდეს და არა ტექსტის

2021-11-01 10:24 UTC, AnaRusadze commented on app/src/main/java/com/example/movieapp/movies_detail/MoviesDetailScreen.kt
> +class MoviesDetailScreen : BaseFragment<MoviesDetailScreenFragmentBinding>(MoviesDetailScreenFragmentBinding::inflate) {
screen-ის მაგივრად fragment ჯობია

2021-11-01 10:24 UTC, AnaRusadze commented on app/src/main/java/com/example/movieapp/movies_detail/MoviesDetailScreen.kt
> +                        detailMovieRatingTxt.text = "Rating: " + it.data.voteAverage.toString()
ლოგიკები ვიუმოდელში გადაიტანე

2021-11-03 23:33 UTC, AleksandreGalogreBaramidze commented on app/src/main/java/com/example/movieapp/adapters/HomeRecyclerAdapter.kt
> +        data.forEach { favoriteMovies.add(Movie.Result(it.poster, it.id, "unknown", "unknown", 0.0, "unknown", "unknown","",false, null)) }
done

2021-11-03 23:33 UTC, AleksandreGalogreBaramidze commented on app/src/main/java/com/example/movieapp/adapters/HomeRecyclerAdapter.kt
> +        holder.binding.mainImage.load(holder.binding.root.context, BASE_PICTURE_URL + (item.backdrop_path))
done

2021-11-03 23:34 UTC, AleksandreGalogreBaramidze commented on app/src/main/java/com/example/movieapp/di/Module.kt
> +    fun getMoviesData(): RetrofitService = Retrofit.Builder().baseUrl(BASE_URL).addConverterFactory(GsonConverterFactory.create()).build().create(RetrofitService::class.java)
done

2021-11-03 23:34 UTC, AleksandreGalogreBaramidze commented on app/src/main/java/com/example/movieapp/movies_detail/MoviesDetailScreenViewModel.kt
> +    }
done

2021-11-03 23:34 UTC, AleksandreGalogreBaramidze commented on app/src/main/java/com/example/movieapp/adapters/HomeRecyclerAdapter.kt
> +class HomeRecyclerAdapter : RecyclerView.Adapter<HomeRecyclerAdapter.ViewHolder>() {
done

2021-11-03 23:34 UTC, AleksandreGalogreBaramidze commented on app/src/main/java/com/example/movieapp/adapters/HomeRecyclerAdapter.kt
> +        holder.binding.mainImage.setOnClickListener {
done

2021-11-03 23:34 UTC, AleksandreGalogreBaramidze commented on app/src/main/java/com/example/movieapp/movies/Movies.kt
done

2021-11-03 23:34 UTC, AleksandreGalogreBaramidze commented on app/src/main/java/com/example/movieapp/movies/Movies.kt
> +    private var internetCheckerBoolean: Boolean? = null
done

2021-11-03 23:34 UTC, AleksandreGalogreBaramidze commented on app/src/main/java/com/example/movieapp/movies/Movies.kt
> +    private fun connectionHandler() {
done

2021-11-03 23:34 UTC, AleksandreGalogreBaramidze commented on app/src/main/java/com/example/movieapp/movies/Movies.kt
> +                        if(it.message == "Unable to resolve host \"api.themoviedb.org\": No address associated with hostname"){
done

2021-11-03 23:34 UTC, AleksandreGalogreBaramidze commented on app/src/main/java/com/example/movieapp/movies_detail/MoviesDetailScreen.kt
> +class MoviesDetailScreen : BaseFragment<MoviesDetailScreenFragmentBinding>(MoviesDetailScreenFragmentBinding::inflate) {
done

2021-11-03 23:34 UTC, AleksandreGalogreBaramidze commented on app/src/main/java/com/example/movieapp/movies_detail/MoviesDetailScreen.kt
> +                        detailMovieRatingTxt.text = "Rating: " + it.data.voteAverage.toString()
done

2021-11-03 23:35 UTC, giorgiqemoklidze approved these changes

2021-11-04 10:57 UTC, AnaRusadze requested changes

2021-11-04 10:57 UTC, AnaRusadze commented on app/src/main/java/com/example/movieapp/api/RetrofitService.kt
> +        api_Key: String = KEY
ინტერსეპტორი დაამატე

2021-11-04 10:57 UTC, AnaRusadze commented on app/src/main/java/com/example/movieapp/database/Entity.kt
> +data class Entity (
MovieEntity

2021-11-04 10:57 UTC, AnaRusadze commented on app/src/main/java/com/example/movieapp/ui/adapters/SetScrollListener.kt
> +        val moreThanShowedItems = recyclerLayoutManager.itemCount >= 20
ფეიჯის საიზი გარედან უნდა გადაეწოდებოდეს და კონსტანტა უნდა იყოს. ლისენერი სხვა ზომების მიმართაც მოქნილი იქნება

2021-11-04 10:57 UTC, AnaRusadze commented on app/src/main/java/com/example/movieapp/ui/base_fragment/BaseFragment.kt
> +        initFragment(viewModel)
onBindViewModel-ს initFragment გირჩევნია რომ ერქვას:?

2021-11-04 10:57 UTC, AnaRusadze commented on app/src/main/java/com/example/movieapp/ui/movies/MoviesFragment.kt
> +        val bindDialog = DialogBinding.inflate(layoutInflater)
ჯობია, რომ dialog და dialogBinding ერქვას ცვლადებს

2021-11-04 10:57 UTC, AnaRusadze commented on app/src/main/java/com/example/movieapp/ui/movies/MoviesFragment.kt
> +        observe(viewModel)
onBindViewModel მაგისთვის იყო, რომ ობსერვისთვის ცალკე ფუნქცია არ გქონოდა

2021-11-04 10:57 UTC, AnaRusadze commented on app/src/main/java/com/example/movieapp/ui/movies/MoviesFragmentViewModel.kt
> +    private var _livedata = MutableLiveData<ApiErrorHandling<Movie>>()
ცუდი სახელია უბრალოდ liveData ცვლადისთვის. ფრაგმენტში ვერ მივხვდი რისი იყო

2021-11-04 10:57 UTC, AnaRusadze commented on app/src/main/java/com/example/movieapp/ui/movies_detail/MoviesDetailFragment.kt
> +                        ViewModel.favoriteMovies(Entity(id = safeArgs.id, pictureUrl, title = ""))
title = "" ?

2021-11-04 10:57 UTC, AnaRusadze commented on app/src/main/java/com/example/movieapp/ui/splash/SplashScreen.kt
> +class SplashScreen : Fragment() {
იდეაში სფლეშ სქრინიც ბეიზ ფრაგმენტის ნაწილი უნდა იყოს და ვიუმოდელის ჩაწოდებაზე პრობლემა არ გექნებოდა, რომ ბეიზ ვიუმოდელი გქონოდა

2021-11-04 11:30 UTC, AleksandreGalogreBaramidze commented on app/src/main/java/com/example/movieapp/database/Entity.kt
> +data class Entity (
done

2021-11-04 11:30 UTC, AleksandreGalogreBaramidze commented on app/src/main/java/com/example/movieapp/ui/adapters/SetScrollListener.kt
> +        val moreThanShowedItems = recyclerLayoutManager.itemCount >= 20
done

2021-11-04 11:31 UTC, AleksandreGalogreBaramidze commented on app/src/main/java/com/example/movieapp/ui/base_fragment/BaseFragment.kt
> +        initFragment(viewModel)
done

2021-11-04 11:31 UTC, AleksandreGalogreBaramidze commented on app/src/main/java/com/example/movieapp/ui/movies/MoviesFragment.kt
> +        val bindDialog = DialogBinding.inflate(layoutInflater)
done

2021-11-04 11:34 UTC, AleksandreGalogreBaramidze commented on app/src/main/java/com/example/movieapp/ui/movies/MoviesFragment.kt
> +        observe(viewModel)
ეგრე კოდი ნაკლებად გარჩევადი არ გახდება?

2021-11-04 11:34 UTC, AleksandreGalogreBaramidze commented on app/src/main/java/com/example/movieapp/ui/movies/MoviesFragmentViewModel.kt
> +    private var _livedata = MutableLiveData<ApiErrorHandling<Movie>>()
done

2021-11-04 11:46 UTC, AleksandreGalogreBaramidze commented on app/src/main/java/com/example/movieapp/ui/movies_detail/MoviesDetailFragment.kt
> +                        ViewModel.favoriteMovies(Entity(id = safeArgs.id, pictureUrl, title = ""))
ეს უბრალოდ დეფოლტ ველიუში გავიტანე და საღამოსკენ ვაფშე ამოვიღებ თაითლს

2021-11-04 12:00 UTC, GiorgiMamagulashvili16 approved these changes

2021-11-05 12:58 UTC, merged